version: "3.8"
services:
  calc-api:
    image: verdantwinds/lbg-grad-compose-api
    build: ./calculator-api
    ports:
      - "8081:8080"
  front-a:
    image: verdantwinds/lbg-grad-compose-front-a
    build:
      context: ./frontend-1
    ports:
      - "80:80"
  front-b:
    image: verdantwinds/lbg-grad-compose-front-b
    build:
      context: ./frontend-2
    ports:
      - "81:80"
